(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Stachowski,, Welcome to Coot version 0.9.8.92")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Stachowski,. Welcome to Coot 0.9.8.92")
(set-display-lists-for-maps 0)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(get-eds-pdb-and-mtz "1uyl")
(handle-read-draw-molecule-with-recentre "coot-download/pdb1uyl.ent" 1)
(make-and-draw-map "coot-download/1uyl_map.mtz" "FWT" "PHWT" "" 0 0)
(make-and-draw-map "coot-download/1uyl_map.mtz" "DELFWT" "PHDELWT" "" 0 1)
(set-clipping-front -0.02)
(set-clipping-back -0.04)
(set-clipping-front 0.06)
(set-clipping-back 0.14)
(set-clipping-front 0.62)
(set-clipping-back 1.18)
(set-clipping-front 0.82)
(set-clipping-back 1.02)
(set-add-alt-conf-split-type-number 1)
