filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Stachowski,, Welcome to Coot version 0.9.8.92")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Stachowski,. Welcome to Coot 0.9.8.92")
set_display_lists_for_maps (0)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
;; # DIRECT SCHEME ((get-eds-pdb-and-mtz "1uyl"))
handle_read_draw_molecule_with_recentre ("coot-download/pdb1uyl.ent", 1)
make_and_draw_map ("coot-download/1uyl_map.mtz", "FWT", "PHWT", "", 0, 0)
make_and_draw_map ("coot-download/1uyl_map.mtz", "DELFWT", "PHDELWT", "", 0, 1)
set_add_alt_conf_split_type_number (1)
